services:
  web:
    image: php:7.2-apache
    build:
      context: .
    container_name: prestashop-web
    ports:
      - "8080:80"
    volumes:
      - ./prestashop:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: root
    command: apache2-foreground

  db:
    image: mysql:5.7
    container_name: prestashop-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: